server:
  port: 9004
spring:
  application:
    #同时也是dubbo服务dubbo.application.name
    name: spring-cloud-alibaba-dubbo-user-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #注册中心地址
        ip: localhost #手动指定往nacos注册的ip地址
        username: nacos
        password: nacos
  main:
    allow-bean-definition-overriding: true    #spring boot 2.1以上版本需要设定
#健康检查地址:http://localhost:9004/actuator/nacosdiscovery
management:
  endpoints:
    web:
      exposure:
        include: "*"

#dubbo的配置
dubbo:
  scan:
      #配置扫描暴露出去的dubbo服务实现类
    base-packages: com.kim.spring.cloud.alibaba.dubbo.user.provider.service
  protocol:
    name: dubbo #dubbo协议
    port: -1  #协议端口，-1表示自增端口，从20880开始
  registry:
    address: spring-cloud://localhost #挂载到springcloud注册中心
  cloud:
    #不需要订阅则置空
    subscribed-services: ""