server:
  port: 9011
spring:
  application:
    name: rocketmq-stream
  cloud:
    stream:
      rocketmq:
        binder:
        name-server: 101.34.74.116:9876
        bindings:
          mychannel:    #通道名字，任意取
            consumer:     #消费者信息配置
              enable: true
              tags: TopicTest
              sql:  a>=3
              delayLevelWhenNextConsume: 0  #并发消费重试策略，0表示由broker的策略决定
              suspendCurrentQueueTimeMillis: 1000 #顺序消费重试间隔时间，单位：毫秒
            producer:   #生产者信息配置
              enable: true
              group:  rocketmq-stream-producer
              maxMessageSize: 8249344   #最大消息大小：单位：byte
              transactional: false  #是否兼容事务消息
              sync: false   #是否同步发送消息
              vipChannelEnabled: true
              sendMessageTimeout: 3000
              compressMessageBodyThreshold: 4096  #超过4K的消息将被压缩
              retryTimesWhenSendFailed: 2   #发送失败将重试2次发送
              retryTimesWhenSendAsyncFailed: 2  #异步发送消息失败将重试2次发送
              retryNextServer: false #当内部发送失败时指示是否重试另一个broker
#swagger
swagger:
  enabled: true
  base-package: com.kim.spring.cloud.alibaba.rocketmq.stream.controller