server:
  port: 9011
spring:
  application:
    name: rocketmq-stream
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 101.34.74.116:9876    #rocketmq的broker链接地址
        bindings:     #output是消息生产者配置，input为消息消费者配置
          output1:
            producer:
              group: rocketmq-stream-output1
              sync: true
          output2:
            producer:
              group: rocketmq-stream-output2
              transactional: true
          input1:
            consumer:
              tags: tagA
              sql: a>=3
              orderly: false
              concurrency: 5
          input2:
            consumer:
              tags: tagA
              orderly: true
      bindings:
        output1:    #通道名字，任意取
          destination: TopicTest
          content-type: application/json
        output2:
          destination: TransactionMsg
          content-type: application/json
        input1:
          destination: TopicTest
          content-type: application/json
          group: rocketmq-stream-input1
        input2:
          destination: TransactionMsg
          content-type: application/json
          group: rocketmq-stream-input2

#swagger
swagger:
  enabled: true
  base-package: com.kim.spring.cloud.alibaba.rocketmq.stream.controller

logging:
  lever:
    com.alibaba.cloud.stream.binder.rocketmq: debug


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always