server:
  port: 9010
spring:
  application:
    name: rocketmq-spring-consumer

rocketmq:
  name-server: 101.34.74.116:9876   #nameserver服务器地址
  consumer:
    access-key: rocketmq1
    secret-key: 12345678
