server:
  port: 9005
spring:
  application:
    name: spring-cloud-alibaba-dubbo-user-comsumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #注册中心地址
        ip: localhost #手动指定往nacos注册的ip地址
        username: nacos
        password: nacos
  main:
    allow-bean-definition-overriding: true    #spring boot 2.1以上版本需要设定
#健康检查地址:http://localhost:9004/actuator/nacosdiscovery
management:
  endpoints:
    web:
      exposure:
        include: "*"

#dubbo的配置
dubbo:
  registry:
    address: spring-cloud://localhost #挂载到springcloud注册中心
  protocol:
    name: dubbo #dubbo协议
    port: -1  #协议端口，-1表示自增端口，从20880开始
  cloud:
    #从注册中心订阅dubbo服务，多个服务用,隔开
    subscribed-services: spring-cloud-alibaba-dubbo-user-provider
